config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Base
  devise_for :admins
  devise_for :users

  # Admin management
  require "sidekiq/web"
  namespace 'administration' do
    resources :items, :orders, :admins, :users
  end
  authenticate :admin do mount Sidekiq::Web => '/sidekiq' end
  authenticated :admin do
    root 'administration/items#index', as: :admin_root
  end

  # Shop
  root to: 'items#index'
  resources :charges, only: %i[new create]
  resources :items, only: %i[index show] do
    get 'page/:page', action: :index, on: :collection
  end
  resource :basket, only: [:show]
  resources :orders, only: %i[index show]
  get '/orders/:id/close', to: 'orders#close', as: 'close_order'
  post '/orders/:id/close', to: 'orders#close'
  resources :order_items, only: %i[create update destroy]

  # User order
  resources :users, only: %i[show] do
    resources :orders, only: %i[index show]
  end
end

app/controllers/baskets_controller.rb
# frozen_string_literal: true

class BasketsController < ApplicationController
  before_action :authenticate_user!

  def show
    @order = current_order
  end
end

app/views/baskets/_basket_row.html.erb
<div class="card p-4">
  <h4><%= item.name %></h4>
  <%= form_for order_item, remote: true do |f| %>
  <h5>Prix unitaire : <%= order_item.unit_price %>€</h5>
  <br>
    <div class="input-group">
      <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
      <%= f.hidden_field :item_id, value: item.id %>
      <div class="btn-group">
        <%= f.submit "Actualiser la quantité", class: "btn btn-primary" %>
        <%= link_to "Supprimer", order_item, { data: { confirm: "Voulez vous vraiment supprimer le produit'#{order_item.item.name}' de votre panier?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
      </div>
    </div>
    <br>
    <h5 class="text-right">Total : <%= order_item.total_price %>€</h5>
  <% end %>
</div>

app/views/baskets/_shopping_basket.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<% if @order.order_items.size == 0 %>
  <p class="text-center">
    Il n'y a aucun article dans votre panier. Veuillez <%= link_to "revenir en arrière", root_path %> et ajouter quelques articles à votre panier.
  </p>
<% else %>
  <% @order.order_items.each do |order_item| %>
    <%= render 'baskets/basket_row', item: order_item.item, order_item: order_item, show_total: true %>
  <% end %>
<% end %>

app/views/baskets/_stripe_pay_button.html.erb
<%= form_tag charges_path(id: @order.id)do %>
<article>
  <% if flash[:error].present? %>
    <div id="error_explanation">
      <p><%= flash[:error] %></p>
    </div>
  <% end %>
</article>

<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
        data-description="Pay me!"
        data-amount="<%= @order.subtotal * 100 %>"
        data-locale="auto"></script>
<% end %>

app/views/baskets/show.html.erb
<div class="shopping-basket">
  <%= render "shopping_basket" %>
</div>
<center>
	<br>
	<h4>Total du panier : <%= current_order.subtotal %>€</h4>
	<br>

	<% if current_order.subtotal > 0 %>
		<div id="stripe-button">
	  	<%= render  "stripe_pay_button" %>
		</div>
	<% end %>
</center>