config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Base
  devise_for :admins
  devise_for :users

  # Admin management
  require "sidekiq/web"
  namespace 'administration' do
    resources :items, :orders, :admins, :users
  end
  authenticate :admin do mount Sidekiq::Web => '/sidekiq' end
  authenticated :admin do
    root 'administration/items#index', as: :admin_root
  end

  # Shop
  root to: 'items#index'
  resources :charges, only: %i[new create]
  resources :items, only: %i[index show] do
    get 'page/:page', action: :index, on: :collection
  end
  resource :basket, only: [:show]
  resources :orders, only: %i[index show]
  get '/orders/:id/close', to: 'orders#close', as: 'close_order'
  post '/orders/:id/close', to: 'orders#close'
  resources :order_items, only: %i[create update destroy]

  # User order
  resources :users, only: %i[show] do
    resources :orders, only: %i[index show]
  end
end

app/models/item.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: items
#
#  id                    :bigint(8)        not null, primary key
#  name                  :string
#  description           :text
#  has_discount          :boolean          default(FALSE)
#  original_price        :decimal(12, 2)
#  discounted_percentage :integer
#  active                :boolean          default(TRUE)
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  image_url             :string
#

class Item < ApplicationRecord
  has_one :stock, dependent: :destroy
  has_one_attached :image
  has_many :order_items, dependent: :destroy

  validates :name, presence: true, length: { minimum: 3 }
  validates :original_price, presence: true, allow_nil: false
  validates :has_discount, default: false
  validates :discounted_percentage,
            numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }

  scope :active, lambda { where(active: true) }
  scope :sorted_by_price, -> { order("original_price ASC") }
  scope :sorted_by_name, lambda { order("name ASC") }
  scope :newest_first, lambda { order("created_at DESC") }
  scope :with_discount, lambda { where(has_discount: true) }
  scope :without_discount, lambda { where(has_discount: false) }
  paginates_per 15

  def price
    has_discount ? (original_price.to_f * (1 - discounted_percentage.to_f / 100)).round(2) : original_price.to_f
  end
end

app/controllers/administration/admins_controller.rb
# frozen_string_literal: true

module Administration
  class AdminsController < AdministrationController
    def index
      @admins = Admin.all
    end
  end
end

app/controllers/administration/items_controller.rb
# frozen_string_literal: true

module Administration
  class ItemsController < AdministrationController
    def index
      @items = Item.sorted_by_name
    end

    def show
      @item = Item.find(params[:id])
    end

    def new
      @item = Item.new
    end

    def edit
      @item = Item.find(params[:id])
    end

    def destroy
      item = Item.find(params[:id])
      item.destroy
      flash[:notice] = "Product has been deleted successfuly"
      redirect_to administration_items_path
    end

    def create
      @item = Item.new(item_params)
      item_valid?(@item)
      redirect_to administration_items_path
    end

    def update
      item = Item.find(params[:id])
      update_item(item)
      item_valid?(item)
      redirect_to administration_items_path
    end

    private

    def item_params
      params.require(:item).permit(:name, :discounted_percentage, :original_price, :active, :description, :image)
    end

    def item_valid?(item)
      if item.valid?
        item.save
        flash[:notice] = "Produit mis à jour"
      else
        flash[:alert] = item.errors.full_messages
      end
    end

    def update_item(item)
      item.update(item_params)
      item.has_discount = params[:item][:discount_percentage] != 0
    end
  end
end

app/controllers/administration/orders_controller.rb
# frozen_string_literal: true

module Administration
  class OrdersController < AdministrationController
    def index
      @orders = Order.all
    end

    def show
      @order = Order.find(params[:id])
    end

    def update
      order = Order.find(params[:id])
      update_order(order)
    end

    def edit
      @order = Order.find(params[:id])
    end

    private

    def order_params
      params.require(:order).permit(:order_status_id)
    end

    def update_order(order)
      result = order.update(order_params)
      if result
        order.update(order_params)
        flash[:notice] = "Commande mise à jour"
        redirect_to administration_orders_path
      else
        flash[:alert] = order.errors.full_messages
      end
    end
  end
end

app/controllers/administration/users_controller.rb
# frozen_string_literal: true

module Administration
  class UsersController < AdministrationController
    def index
      @users = User.all
    end
  end
end

app/controllers/administration_controller.rb
# frozen_string_literal: true

class AdministrationController < ApplicationController
  before_action :authenticate_admin!
  layout "administration"
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  def index
    @items = Item.active.page(params[:page])
    @order_items = current_order.order_items.new
  end

  def show
    @item = Item.find(params[:id])
    @order_item = current_order.order_items.find_by(item_id: @item.id) || current_order.order_items.new
  end
end

app/views/administration/items/_item_list.html.erb
<% @items.each do |item| %>
  <%= form_for item, url: administration_item_path(item), method: :patch  do |f| %>
  <tr>
    <td><%= item.id %></td>
    <td><%= item.name %></td>
    <td><%= item.description %></td>
    <td><%= item.original_price.to_f %></td>
    <td><%= f.text_field(:discounted_percentage, value: item.discounted_percentage) %></td>
    <td><%= item.price %></td>
    <td><%= item.active %></td>
    <td><%= f.submit 'Mettre à jour', class: "btn btn-primary" %></td>
    <td><%= link_to 'Modifier', edit_administration_item_path(item), class: "btn btn-info" %></td>
    <td><%= link_to 'Supprimer', administration_item_path(item), method: :delete, confirm: "Are you sure ?", class: "btn btn-danger" %></td>
  </tr>
  <% end %>
<% end %>

app/views/administration/items/edit.html.erb
<div class="container">
  <h1>Modification produit <%= @item.name %></h1>

  <%= form_for @item, url: administration_item_path(@item), method: :patch  do |f| %>
    <p><%= f.label 'Nom produit' %></p>
    <p><%= f.text_field(:name, value: @item.name) %><p>
    <p><%= f.label 'description produit' %></p>
    <p><%= f.text_field(:description, value: @item.description) %><p>
    <p><%= f.label 'Prix de base' %></p>
    <p><%= f.number_field(:original_price, value: @item.original_price) %><p>
    <p><%= f.label 'Remise sur produit' %></p>
    <p><%= f.number_field(:discounted_percentage, value: @item.discounted_percentage) %><p>
    <p><%= f.label 'Status produit' %></p>
    <p><%= f.select(:active, options_for_select([['Valider', true], ['Désactiver', false]])) %></p>
    <p><%= f.submit 'Mettre à jour' %></p>
  <% end -%>
</div>

app/views/administration/items/index.html.erb
<main class="content">
  <div class="container-fluid p-0">
    <h1 class="h3 mb-3">Liste des produits</h1>
    <h2 class="h5 mb-3"><%= link_to 'Ajouter un produit', new_administration_item_path %></h2>
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="table-responsive">
            <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th>Item Id</th>
                  <th>Nom</th>
                  <th>Description</th>
                  <th>Prix de base</th>
                  <th>Remise en %</th>
                  <th>Prix actuel</th>
                  <th>Status</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <%= render('item_list') %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/administration/items/new.html.erb
<div class="container">
  <h1>Ajouter un produit</h1>

  <%= form_for @item, url: administration_items_path(@item) do |f| %>
    <p><%= f.label 'Nom du produit' %>
    <%= f.text_field :name, autofocus: true, class: "form-control" %><p>
    <p><%= f.label 'description produit' %>
    <%= f.text_field :description, class: "form-control" %><p>
    <p><%= f.label :image %>
    <%= f.file_field :image, class: "" %><p>
    <p><%= f.label 'Prix de base' %>
    <%= f.number_field :original_price, class: "form-control" %><p>
    <p><%= f.label 'Remise sur produit en %' %>
    <%= f.number_field :discounted_percentage, value: 0, class: "form-control" %><p>
    <p><%= f.label 'Status produit' %>
    <%= f.select(:active, options_for_select([['Valider', true], ['Désactiver', false]]), class: "form-control") %></p>
    <p><%= f.submit 'Créer', class: "btn btn-primary" %></p>
  <% end -%>
</div>

app/views/administration/items/show.html.erb
<h1>Administration/items#show</h1>