config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Base
  devise_for :admins
  devise_for :users

  # Admin management
  require "sidekiq/web"
  namespace 'administration' do
    resources :items, :orders, :admins, :users
  end
  authenticate :admin do mount Sidekiq::Web => '/sidekiq' end
  authenticated :admin do
    root 'administration/items#index', as: :admin_root
  end

  # Shop
  root to: 'items#index'
  resources :charges, only: %i[new create]
  resources :items, only: %i[index show] do
    get 'page/:page', action: :index, on: :collection
  end
  resource :basket, only: [:show]
  resources :orders, only: %i[index show]
  get '/orders/:id/close', to: 'orders#close', as: 'close_order'
  post '/orders/:id/close', to: 'orders#close'
  resources :order_items, only: %i[create update destroy]

  # User order
  resources :users, only: %i[show] do
    resources :orders, only: %i[index show]
  end
end

app/models/item.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: items
#
#  id                    :bigint(8)        not null, primary key
#  name                  :string
#  description           :text
#  has_discount          :boolean          default(FALSE)
#  original_price        :decimal(12, 2)
#  discounted_percentage :integer
#  active                :boolean          default(TRUE)
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  image_url             :string
#

class Item < ApplicationRecord
  has_one :stock, dependent: :destroy
  has_one_attached :image
  has_many :order_items, dependent: :destroy

  validates :name, presence: true, length: { minimum: 3 }
  validates :original_price, presence: true, allow_nil: false
  validates :has_discount, default: false
  validates :discounted_percentage,
            numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }

  scope :active, lambda { where(active: true) }
  scope :sorted_by_price, -> { order("original_price ASC") }
  scope :sorted_by_name, lambda { order("name ASC") }
  scope :newest_first, lambda { order("created_at DESC") }
  scope :with_discount, lambda { where(has_discount: true) }
  scope :without_discount, lambda { where(has_discount: false) }
  paginates_per 15

  def price
    has_discount ? (original_price.to_f * (1 - discounted_percentage.to_f / 100)).round(2) : original_price.to_f
  end
end

app/controllers/administration/items_controller.rb
# frozen_string_literal: true

module Administration
  class ItemsController < AdministrationController
    def index
      @items = Item.sorted_by_name
    end

    def show
      @item = Item.find(params[:id])
    end

    def new
      @item = Item.new
    end

    def edit
      @item = Item.find(params[:id])
    end

    def destroy
      item = Item.find(params[:id])
      item.destroy
      flash[:notice] = "Product has been deleted successfuly"
      redirect_to administration_items_path
    end

    def create
      @item = Item.new(item_params)
      item_valid?(@item)
      redirect_to administration_items_path
    end

    def update
      item = Item.find(params[:id])
      update_item(item)
      item_valid?(item)
      redirect_to administration_items_path
    end

    private

    def item_params
      params.require(:item).permit(:name, :discounted_percentage, :original_price, :active, :description, :image)
    end

    def item_valid?(item)
      if item.valid?
        item.save
        flash[:notice] = "Produit mis à jour"
      else
        flash[:alert] = item.errors.full_messages
      end
    end

    def update_item(item)
      item.update(item_params)
      item.has_discount = params[:item][:discount_percentage] != 0
    end
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  def index
    @items = Item.active.page(params[:page])
    @order_items = current_order.order_items.new
  end

  def show
    @item = Item.find(params[:id])
    @order_item = current_order.order_items.find_by(item_id: @item.id) || current_order.order_items.new
  end
end

app/views/items/index.html.erb
<h1 class="text-center">Bienvenue à Magic Project</h1>
<h6 class="text-center">
  <small class="text-muted h6">Les meilleures cartes à prix Ruby</small>
</h6> 
<br><br>

<div class="row">
  <% @items.each do |item| %>
    <div class="card col-lg-3 col-md-6 col-xs-12">
      <a href="<%= item_path(item.id) %>">
      <img class="card-img-top" src="<%= item.image.attached? ? item.image : item.image_url %>" alt="<%= item.name %>">
      <div class="card-body">
        <h5 class="card-title"><%= item.name %></a></h5>
        <p class="card-text"><%= item.description %></p>
        <% if item.discounted_percentage > 0 %>
          <p class="card-text">Prix avant réduction : <%= item.original_price.to_f %>€</p>
          <p class="card-text">Pourcentage de remise : <%= item.discounted_percentage %>%</p>
          <p class="card-text">Prix après réduction : <%= item.price %>€</p>
        <% else %>
          <p class="card-text">Prix : <%= item.original_price.to_f %>€</p>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class='digg_pagination'>
  <%= paginate @items %>
</div>

app/views/items/show.html.erb
<div class="container jumbotron">
  <div class="row">
    <div class="col-lg-3 col-md-4 col-xs-12">
      <% if @item.image.attached? %>
        <%= image_tag(@item.image, class: "items__image") %> 
      <% elsif !@item.image_url.nil? %>
        <%= image_tag(@item.image_url, class: "items__image") %>     
      <% end %>
    </div>

    <div class="col-lg-9 col-md-8 col-xs-12">
      <h1><%= @item.name %></h1>
      <% if @item.discounted_percentage > 0 %>
	      <p>Prix de départ : <%= @item.original_price.to_f %>€</p>
	      <p>Pourcentage de remise : <%= @item.discounted_percentage %>%</p>
      <% end %>
      <p class="text-justify">Texte : <%= @item.description %></p>
      <p>Prix : <b><%= @item.price %>€</b></p>
    </div>
  </div>
  <br>

  <div class="" id="add_to_cart">
    <%= render  "layouts/add_to_cart", item: @item, order_item: @order_item %>  
  </div>
</div>