config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Base
  devise_for :admins
  devise_for :users

  # Admin management
  require "sidekiq/web"
  namespace 'administration' do
    resources :items, :orders, :admins, :users
  end
  authenticate :admin do mount Sidekiq::Web => '/sidekiq' end
  authenticated :admin do
    root 'administration/items#index', as: :admin_root
  end

  # Shop
  root to: 'items#index'
  resources :charges, only: %i[new create]
  resources :items, only: %i[index show] do
    get 'page/:page', action: :index, on: :collection
  end
  resource :basket, only: [:show]
  resources :orders, only: %i[index show]
  get '/orders/:id/close', to: 'orders#close', as: 'close_order'
  post '/orders/:id/close', to: 'orders#close'
  resources :order_items, only: %i[create update destroy]

  # User order
  resources :users, only: %i[show] do
    resources :orders, only: %i[index show]
  end
end

app/views/layouts/_add_to_cart.html.erb
<% if user_signed_in? %> 
  <% if @order_item.new_record? %>
    <%= form_for order_item, remote: true do |f| %>
      <div class="input-group">
        <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
        <%= f.hidden_field :item_id, value: item.id %>
        <%= f.submit "Ajouter au panier", class: "btn btn-primary" %>
      </div>
    <% end %> 
  <% else %>
    <%= link_to 'Retour au shop', items_path, class: "btn btn-primary" %>
    <%= link_to 'Finaliser votre commande', basket_path, class: "btn btn-primary" %>
  <% end %>
  <% else %>
      <%= link_to 'Se connecter', new_user_session_path, class: "btn btn-primary" %>
<% end %>

app/views/layouts/_basket_text.html.erb
<%= link_to "#{current_order.order_items.size} Produit(s) au panier ( #{current_order.subtotal}€ )", basket_path, class: "btn btn-link text-white" %>

app/views/layouts/_footer.html.erb
<footer>
	<div class="row">
		<div class="col-lg-9 col-md-9 col-xs-12">
			<p class="footer-title">Magic Project<br> © 2019</p>
		</div>
		<div class="col-lg-3 col-md-3 col-xs-12">
			<p class="footer-title">Admin</p>
				<ul>
					<% if admin_signed_in? %>
						<li><%= link_to "Espace d'administration", admin_root_path, :class => "footer-text" %></li>
						<li><%= link_to "Se déconnecter", destroy_admin_session_path, method: :delete, :class => "footer-text" %></li>
					<% else %>
						<li><%= link_to "S'inscrire", new_admin_registration_path, :class => "footer-text" %></li>
						<li><%= link_to "Se connecter", admin_session_path, :class => "footer-text" %></li>
					<% end %>
				</ul>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <%= link_to 'Magic Project', root_path, class: "navbar-brand" %>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav d-flex justify-content-between text-center w-100">
      <li class="nav-item">
        <%= link_to 'Accueil', items_path, class: "nav-link" %>
      </li>
      
      <% if user_signed_in? %>
      <li class="nav-item">
        <span class="basket-text"><%= render 'layouts/basket_text' %></span>
      </li>
      
      <li class="nav-item dropdown d-flex flex-column">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Profil </a>
        <div class="dropdown-menu float-right header-dropdown" aria-labelledby="navbarDropdown">
          <%= link_to 'Liste des commandes', user_orders_path(current_user) , class: 'dropdown-item'%><hr>
          <%= link_to 'Se Déconnecter', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          <%= link_to 'Changer mot de passe', edit_user_registration_path , class: 'dropdown-item'%>
        </div>
      </li>
      
      <% else %>
        <li class="nav-item">
          <%= link_to "S'inscrire", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Se connecter', new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/administration.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Magic Project Admin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'administration', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <div class="d-flex">
        
        <%= render "layouts/template/sidebar" %>

        <div class="main">

          <%= render "layouts/template/navbar" %>
          
          <%= render "layouts/shared/flash_messages" %>
          
          <main class="content">
            <div class="container-fluid p-0">
              <%= yield %>
            </div>
          </main>
        
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Magic Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <%= render partial: "layouts/header" %>
    </header>
    <div class="container">
      <main>
        <%= render "layouts/shared/flash_messages" %>
        <br><br>
        <%= yield %>
      </main>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>